-- Migration: create_quizzes
-- One quiz per bill. Generated by the generate-bill-quiz Edge Function.
-- questions is a JSONB array: [{question, options, correct, explanation}]

create table public.quizzes (
  id           uuid primary key default gen_random_uuid(),
  bill_id      text not null references public.bills(id) on delete cascade unique,
  questions    jsonb not null,
  generated_at timestamptz not null default now(),
  created_at   timestamptz not null default now()
);

-- RLS
alter table public.quizzes enable row level security;

create policy "Quizzes are publicly readable"
  on public.quizzes for select
  using (true);
